source 'https://rubygems.org'
ruby '2.0.0'

gem 'rails', '~>4.0.0'

# database
gem 'pg', '~>0.16.0'

# assets
gem 'sass-rails', '~>4.0.0'
gem 'uglifier', '~>1.3.0'
gem 'coffee-rails', '~>4.0.0'
gem 'jquery-rails', '~>3.0.4'



# turbolinks
gem 'turbolinks', '~>1.3.0'
gem 'jquery-turbolinks', '~>2.0.1'

# json
# gem 'jbuilder', '~> 1.2'

# server
# gem 'unicorn', '~> 4.6.2'
# gem 'rack-timeout', '~> 0.0.4'

# static pages
gem 'high_voltage', '~> 1.2.4'

# authentication
gem 'devise', '~> 3.1.0'

#forms
gem 'simple_form', '~> 3.0.0'

# pagination
gem 'kaminari', '~> 0.14.1'



# urls
gem 'friendly_id', '~> 5.0.0.rc2'

group :production do
  gem 'rails_12factor'
  gem 'rufus-scheduler', '~> 2.0.19'
end

group :development do
  gem 'foreman',           '~> 0.63.0'
  gem 'better_errors',     '~> 0.9.0'
  gem 'binding_of_caller', '~> 0.7.1'
  gem 'xray-rails',        '~> 0.1.6'
  gem 'ffaker'
  gem 'start', '~> 0.0.10'
  gem 'guard'
  gem 'guard-livereload'
  gem 'appbombado_startae'
end

group :test, :development do
  gem 'rspec-rails', '~> 2.14.0'
  gem 'pry-rails',   '~> 0.3.2'
end

gem 'mini_magick'
gem 'carrierwave'
gem 'fog'
gem 'mail_form'
gem 'redactor-rails'




# gem 'start', path: '../start'
